name: Pull-Requests

on:
  pull_request:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install pre-commit
        run: pip install .[dev]
      - name: Run pre-commit
        run: pre-commit run --all-files